name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# Add step to lint code and Dockerfile.
# Add step to build the Docker image.
# Add step to unit tests.
jobs:
  lint-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Lint the Docker image
      uses: hadolint/hadolint-action@v3.1.0

  lint-code:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Lint the Python code with Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app python:3.9-slim bash -c "pip install -r requirements.txt && pip install pylint && pylint **/*.py"
  
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Build the docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Test the Python code with Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app python:3.9-slim bash -c "pip install -r requirements.txt && pip install pytest && pytest"
